import './globals.css'
import type { Metadata } from 'next'
import RegisterModal from "@/components/modals/RegisterModal";
import Navbar from "@/components/navbar/Navbar";
import ToasterProvider from "@/providers/ToasterProvider";
import LoginModal from "@/components/modals/LoginModal";
import getCurrentUser from "@/actions/getCurrentUser";
import Footer from "@/components/Footer";
import getPosts from "@/actions/getPosts";
import ProfileModal from "@/components/modals/ProfileModal";

export const metadata: Metadata = {
  title: 'Modern blog',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser();
  const allPosts = await getPosts();
  return (
    <html lang="en">
      <body>
        <ToasterProvider />
        <RegisterModal />
        <LoginModal />
        <ProfileModal currentUser={currentUser} />
        <Navbar currentUser={currentUser} posts={allPosts}/>
        {children}
        <Footer />
      </body>
    </html>
  )
}
